services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: init-samples-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: init-samples-backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/music_samples
    volumes:
      - ./backend:/app
      - /app/node_modules

    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: init-samples-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: music_samples
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d music_samples"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: