FROM node:22-alpine AS builder

WORKDIR /app

RUN apk add --no-cache ffmpeg

COPY package*.json tsconfig.json ./
RUN npm ci

COPY src ./src
COPY prisma ./prisma 

RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app

RUN apk add --no-cache ffmpeg

COPY package*.json ./

RUN npm ci --only=production

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma 

ENV PORT=8080
ENV NODE_ENV=production

EXPOSE 8080

CMD ["sh", "-c", "npm run db:migrate && node dist/index.js"]